LIB_BUILD_DIR = build

CIMGUI_TARGET = $(LIB_BUILD_DIR)/cimgui/libcimgui.a
GLAD_TARGET = $(LIB_BUILD_DIR)/glad/libglad.a
CGLTF_TARGET = $(LIB_BUILD_DIR)/cgltf/cgltf.a

CIMGUI_INCLUDE_DIR = cimgui
GLAD_INCLUDE_DIR = glad/include
CGLTF_INCLUDE_DIR = cgltf

LIB_TARGETS = $(CIMGUI_TARGET) $(GLAD_TARGET) $(CGLTF_TARGET)
LIB_INCLUDE_PATHS = $(CIMGUI_INCLUDE_DIR) $(GLAD_INCLUDE_DIR) $(CGLTF_INCLUDE_DIR)
